// 2025-2026 Spelling Bee Word List — All 450 words with definitions and parts of speech
// Design: Sunny Candy Kingdom — candy-pop maximalist, touch-first for Fire tablet

export interface Word {
  id: number;
  word: string;
  partOfSpeech: string;
  definition: string;
}

export const ALL_WORDS: Word[] = [
  { id: 1, word: "tag", partOfSpeech: "noun", definition: "a game in which one player chases the others and tries to touch one to make them it." },
  { id: 2, word: "send", partOfSpeech: "verb", definition: "to cause to go or be conveyed to another person or place." },
  { id: 3, word: "deck", partOfSpeech: "noun", definition: "a flat structure that is built next to a house and that has no roof or walls." },
  { id: 4, word: "stuck", partOfSpeech: "verb", definition: "attached by or as if by gluing or plastering." },
  { id: 5, word: "snug", partOfSpeech: "adjective", definition: "at rest, warmly covered, and safe from cold." },
  { id: 6, word: "fish", partOfSpeech: "noun", definition: "a cold-blooded animal that lives in the water and that has a spine, gills, and usually fins." },
  { id: 7, word: "hold", partOfSpeech: "verb", definition: "to keep back : to not loose : to not let go." },
  { id: 8, word: "mind", partOfSpeech: "verb", definition: "to become concerned or troubled : to care, worry." },
  { id: 9, word: "stay", partOfSpeech: "verb", definition: "to remain somewhere or with someone instead of leaving." },
  { id: 10, word: "scrub", partOfSpeech: "verb", definition: "to clean with a rubbing action (as by using a stiff brush)." },
  { id: 11, word: "draw", partOfSpeech: "verb", definition: "to make lines with a pen, a pencil, or another tool in order to create a picture." },
  { id: 12, word: "brown", partOfSpeech: "adjective", definition: "of a color between red and yellow in hue, of medium to low lightness, and of moderate to low saturation." },
  { id: 13, word: "cozy", partOfSpeech: "adjective", definition: "suggesting warmth and homey ease often within smallish or compact quarters." },
  { id: 14, word: "tint", partOfSpeech: "noun", definition: "a usually slight or pale coloration." },
  { id: 15, word: "milk", partOfSpeech: "noun", definition: "a white or yellowish fluid produced by female mammals for the nourishment of their young." },
  { id: 16, word: "yawn", partOfSpeech: "verb", definition: "to take a deep breath with your mouth wide open usually because you're bored or tired." },
  { id: 17, word: "tank", partOfSpeech: "noun", definition: "a large container for holding liquid." },
  { id: 18, word: "want", partOfSpeech: "verb", definition: "to desire or wish for something." },
  { id: 19, word: "crowd", partOfSpeech: "noun", definition: "a large number of people especially when condensed into a compact group without order." },
  { id: 20, word: "pond", partOfSpeech: "noun", definition: "a body of water that is smaller than a lake but larger than a pool." },
  { id: 21, word: "skirt", partOfSpeech: "noun", definition: "the part of an outer garment extending from the waist down that has a free hanging lower edge." },
  { id: 22, word: "sharks", partOfSpeech: "plural noun", definition: "fishes that are usually of medium or large size and that may be active predators or sluggish bottom dwellers." },
  { id: 23, word: "quilt", partOfSpeech: "noun", definition: "a bed covering made of two layers of cloth and having a filling of wool, cotton, or down held in place by stitched designs." },
  { id: 24, word: "twigs", partOfSpeech: "plural noun", definition: "small shoots or branches usually without leaves." },
  { id: 25, word: "taffy", partOfSpeech: "noun", definition: "a candy made usually of molasses or brown sugar boiled until caramelized and pulled until porous and light-colored." },
  { id: 26, word: "comfy", partOfSpeech: "adjective", definition: "giving or promising physical ease, pleasurable feeling, or cheerful well-being." },
  { id: 27, word: "stretch", partOfSpeech: "verb", definition: "to reach out : to extend." },
  { id: 28, word: "tight", partOfSpeech: "adjective", definition: "fitting closely and usually too closely." },
  { id: 29, word: "candy", partOfSpeech: "noun", definition: "a sweet food made with sugar and often flavoring (such as chocolate) and filling." },
  { id: 30, word: "scrunch", partOfSpeech: "verb", definition: "to squeeze together." },
  { id: 31, word: "ruby", partOfSpeech: "noun", definition: "a valuable red gemstone." },
  { id: 32, word: "close", partOfSpeech: "verb", definition: "to block or shut off against entry or passage." },
  { id: 33, word: "tackle", partOfSpeech: "verb", definition: "to come to grips with : to take on." },
  { id: 34, word: "wire", partOfSpeech: "noun", definition: "metal in the form of a usually very flexible thread." },
  { id: 35, word: "skater", partOfSpeech: "noun", definition: "one that glides along on a short board mounted on small wheels propelled by the alternate action of the legs." },
  { id: 36, word: "giant", partOfSpeech: "adjective", definition: "extremely large." },
  { id: 37, word: "bucket", partOfSpeech: "noun", definition: "a typically round and wooden vessel for drawing up water from a well." },
  { id: 38, word: "chance", partOfSpeech: "noun", definition: "opportunity." },
  { id: 39, word: "baskets", partOfSpeech: "plural noun", definition: "lightweight containers in which berries, fruits, or vegetables are packed, shipped, or sold." },
  { id: 40, word: "tender", partOfSpeech: "adjective", definition: "easily broken, cut, or hurt: not hard or tough." },
  { id: 41, word: "paste", partOfSpeech: "verb", definition: "to stick things together using a substance made for this purpose." },
  { id: 42, word: "melon", partOfSpeech: "noun", definition: "either of two soft-fleshed sweet-flavored gourds that are usually eaten raw as a fruit." },
  { id: 43, word: "farmer", partOfSpeech: "noun", definition: "a person who grows crops such as fruits or vegetables, or raises livestock such as cows or pigs." },
  { id: 44, word: "parent", partOfSpeech: "noun", definition: "a father or mother or one who acts as such." },
  { id: 45, word: "tail", partOfSpeech: "noun", definition: "a thin extension of the body that comes out of the back area of many mammals." },
  { id: 46, word: "hockey", partOfSpeech: "noun", definition: "a game played on an ice rink by two teams of six players on skates whose object is to direct a puck into the opponents' goal with a curved stick." },
  { id: 47, word: "slime", partOfSpeech: "noun", definition: "a gluey substance." },
  { id: 48, word: "insects", partOfSpeech: "plural noun", definition: "small invertebrate animals that are more or less obviously segmented (such as spiders, mites, ticks, centipedes, sowbugs)." },
  { id: 49, word: "teeth", partOfSpeech: "plural noun", definition: "the hard bony parts attached to the jaws in the walls of the mouth that serve especially for the seizing and chewing of food." },
  { id: 50, word: "shortcut", partOfSpeech: "noun", definition: "a route more direct or more quickly traveled than the one ordinarily taken." },
  { id: 51, word: "bait", partOfSpeech: "noun", definition: "an enticement used to attract fish or other animals (as to a hook or trap) so that they can be caught." },
  { id: 52, word: "lure", partOfSpeech: "verb", definition: "to attract : to entice." },
  { id: 53, word: "cluster", partOfSpeech: "noun", definition: "a number of similar things grouped together." },
  { id: 54, word: "forest", partOfSpeech: "noun", definition: "a large area of land covered with lots of trees, shrubs and bushes." },
  { id: 55, word: "hollow", partOfSpeech: "adjective", definition: "having an empty space or cavity within : not solid." },
  { id: 56, word: "spinning", partOfSpeech: "verb", definition: "revolving or whirling rapidly." },
  { id: 57, word: "baffling", partOfSpeech: "adjective", definition: "perplexing : confusing." },
  { id: 58, word: "sizzling", partOfSpeech: "adjective", definition: "making a hissing sound." },
  { id: 59, word: "hoist", partOfSpeech: "verb", definition: "to raise : to lift." },
  { id: 60, word: "search", partOfSpeech: "noun", definition: "an endeavor to find, recover, or bring into view." },
  { id: 61, word: "remind", partOfSpeech: "verb", definition: "to cause to remember." },
  { id: 62, word: "mango", partOfSpeech: "noun", definition: "a yellowish red oblong to pear-shaped tropical fruit that has a firm skin and hard central stone." },
  { id: 63, word: "coral", partOfSpeech: "adjective", definition: "of a variable color averaging a deep pink with yellow." },
  { id: 64, word: "jangle", partOfSpeech: "verb", definition: "to cause to sound harshly or inharmoniously." },
  { id: 65, word: "shimmer", partOfSpeech: "verb", definition: "to shine with a tremulous or fitful light : to gleam faintly." },
  { id: 66, word: "blossoms", partOfSpeech: "plural noun", definition: "the usually colorful flowers of a seed plant." },
  { id: 67, word: "swampy", partOfSpeech: "adjective", definition: "water-logged and poorly drained." },
  { id: 68, word: "studded", partOfSpeech: "adjective", definition: "adorned, covered, or protected with solid buttons." },
  { id: 69, word: "focus", partOfSpeech: "verb", definition: "to concentrate attention or effort." },
  { id: 70, word: "distress", partOfSpeech: "noun", definition: "pain, suffering : anguish of body or mind." },
  { id: 71, word: "lessons", partOfSpeech: "plural noun", definition: "classes taught on a single subject." },
  { id: 72, word: "moment", partOfSpeech: "noun", definition: "a point of time : an instant." },
  { id: 73, word: "ajar", partOfSpeech: "adverb", definition: "slightly open." },
  { id: 74, word: "basil", partOfSpeech: "noun", definition: "the dried or fresh leaves of an aromatic of the mint family that is used especially as a seasoning." },
  { id: 75, word: "triple", partOfSpeech: "adjective", definition: "being three times as much or as great or as many." },
  { id: 76, word: "satin", partOfSpeech: "noun", definition: "a smooth fabric with a shiny front and dull back." },
  { id: 77, word: "ahoy", partOfSpeech: "interjection", definition: "used in greeting or beckoning by calling to." },
  { id: 78, word: "signal", partOfSpeech: "noun", definition: "a sound or gesture made to give notice." },
  { id: 79, word: "answer", partOfSpeech: "noun", definition: "something spoken or written in reply : a response to a question, call, summons, or appeal." },
  { id: 80, word: "shuffle", partOfSpeech: "verb", definition: "to slide the feet back and forth without lifting them." },
  { id: 81, word: "dollop", partOfSpeech: "noun", definition: "a lump or blob of something semiliquid or mushy." },
  { id: 82, word: "minnows", partOfSpeech: "plural noun", definition: "small fish common in gravelly streams and attaining a length of about three inches maximum." },
  { id: 83, word: "silver", partOfSpeech: "noun", definition: "a white metallic element that is very easy to shape and is used to make coins, silverware, jewelry and other items." },
  { id: 84, word: "before", partOfSpeech: "adverb", definition: "earlier than." },
  { id: 85, word: "circus", partOfSpeech: "noun", definition: "a spectacular public entertainment given usually in a large tent and made up of acts of physical skill and daring and comedy by clowns." },
  { id: 86, word: "writing", partOfSpeech: "adjective", definition: "of, relating to, or used in or for the act or art of forming letters on a suitable medium to communicate ideas." },
  { id: 87, word: "kitchen", partOfSpeech: "noun", definition: "a place (such as a room) with cooking facilities." },
  { id: 88, word: "sugar", partOfSpeech: "noun", definition: "a sweet crystallizable substance that consists essentially of sucrose and that is colorless or white when pure." },
  { id: 89, word: "awkward", partOfSpeech: "adjective", definition: "lacking dexterity or skill especially in the use of the hands or of instruments : clumsy." },
  { id: 90, word: "seep", partOfSpeech: "verb", definition: "to flow or pass slowly through fine pores or small openings : to ooze." },
  { id: 91, word: "sweet", partOfSpeech: "adjective", definition: "marked by or arising from graciousness, kindness, or sympathy." },
  { id: 92, word: "wheels", partOfSpeech: "plural noun", definition: "round frames that attach to a shaft on which they turn." },
  { id: 93, word: "faint", partOfSpeech: "adjective", definition: "feeble, dizzy, and likely to pass out due to hunger, illness, pain, shock or emotion." },
  { id: 94, word: "fruit", partOfSpeech: "noun", definition: "the reproductive body of a seed plant having an edible more or less sweet pulp associated with the seed." },
  { id: 95, word: "roam", partOfSpeech: "verb", definition: "to go from place to place without a specific purpose or direction : rove, wander." },
  { id: 96, word: "goats", partOfSpeech: "plural noun", definition: "agile hollow-horned ruminant mammals long domesticated for their milk, wool, and flesh." },
  { id: 97, word: "woozy", partOfSpeech: "adjective", definition: "affected with dizziness, mild nausea, or weakness." },
  { id: 98, word: "limbs", partOfSpeech: "plural noun", definition: "legs or arms of a human being." },
  { id: 99, word: "ahead", partOfSpeech: "adverb", definition: "farther in the direction in which a person or thing is going." },
  { id: 100, word: "unicorn", partOfSpeech: "noun", definition: "an imaginary animal that has the body of a horse, the back legs of a stag, the tail of a lion and a single horn in the middle of its head." },
  { id: 101, word: "faraway", partOfSpeech: "adjective", definition: "distant in space." },
  { id: 102, word: "heater", partOfSpeech: "noun", definition: "a device that gives off warmth." },
  { id: 103, word: "pirates", partOfSpeech: "plural noun", definition: "robbers on the high seas." },
  { id: 104, word: "understand", partOfSpeech: "verb", definition: "to comprehend." },
  { id: 105, word: "wooden", partOfSpeech: "adjective", definition: "lacking in ease, grace, charm, liveliness, lifelikeness, interest, or zest : awkward, clumsy, dry, lifeless, dull." },
  { id: 106, word: "leaning", partOfSpeech: "verb", definition: "casting one's weight by inclining or bearing down to one side." },
  { id: 107, word: "breakfast", partOfSpeech: "noun", definition: "the first meal of the day." },
  { id: 108, word: "window", partOfSpeech: "noun", definition: "an opening in a wall or door that usually contains a sheet of glass and that allows light and air in and permits viewing." },
  { id: 109, word: "acrobat", partOfSpeech: "noun", definition: "one who performs gymnastic feats or exercises." },
  { id: 110, word: "message", partOfSpeech: "noun", definition: "a written or oral communication or other transmitted information sent by messenger or by some other means." },
  { id: 111, word: "chocolate", partOfSpeech: "noun", definition: "a small candy with a center (as of fondant, nougat, or nut) and a coating of a food obtained by grinding roasted cacao beans." },
  { id: 112, word: "forepaw", partOfSpeech: "noun", definition: "the foot of a quadruped on a front leg." },
  { id: 113, word: "elephant", partOfSpeech: "noun", definition: "any of a family of thickset extremely large nearly hairless herbivorous mammals that have a snout elongated into a muscular trunk." },
  { id: 114, word: "hedgehog", partOfSpeech: "noun", definition: "any of several nocturnal insectivorous mammals that have hair mixed with prickles or spines and are able to roll themselves up." },
  { id: 115, word: "recipe", partOfSpeech: "noun", definition: "a list of ingredients and a statement of the procedure to be followed in making an item of food or drink." },
  { id: 116, word: "garbage", partOfSpeech: "noun", definition: "trash of any kind." },
  { id: 117, word: "surprise", partOfSpeech: "noun", definition: "something unexpected or astonishing." },
  { id: 118, word: "mermaid", partOfSpeech: "noun", definition: "an imaginary sea creature usually represented as having the upper body of a woman and the lower part like the tail of a fish." },
  { id: 119, word: "bombarded", partOfSpeech: "verb", definition: "attacked vigorously or persistently (as with questions or petitions)." },
  { id: 120, word: "disability", partOfSpeech: "noun", definition: "a physical or mental illness, injury, or condition that incapacitates in any way." },
  { id: 121, word: "incredible", partOfSpeech: "adjective", definition: "hard to believe real or true : unlikely : improbable." },
  { id: 122, word: "leather", partOfSpeech: "noun", definition: "the skin of an animal tanned or otherwise dressed for use to render it relatively soft and flexible when dry." },
  { id: 123, word: "countess", partOfSpeech: "noun", definition: "a woman who holds in her own right the rank of earl or a corresponding rank." },
  { id: 124, word: "nervous", partOfSpeech: "adjective", definition: "fearful of what may be coming." },
  { id: 125, word: "peppercorn", partOfSpeech: "noun", definition: "a dried berry of a plant of the genus Piper." },
  { id: 126, word: "cartwheel", partOfSpeech: "noun", definition: "a sideways handspring with arms and legs extended." },
  { id: 127, word: "raise", partOfSpeech: "verb", definition: "to lift higher." },
  { id: 128, word: "weather", partOfSpeech: "noun", definition: "meteorological or atmospheric condition." },
  { id: 129, word: "zooming", partOfSpeech: "verb", definition: "moving with or making a loud but low hum or buzz." },
  { id: 130, word: "attacked", partOfSpeech: "verb", definition: "began to injure, damage, or eat." },
  { id: 131, word: "turnout", partOfSpeech: "noun", definition: "a gathering of people for a special purpose." },
  { id: 132, word: "eaten", partOfSpeech: "adjective", definition: "taken in through the mouth as food." },
  { id: 133, word: "streetlights", partOfSpeech: "plural noun", definition: "electric lamps usually mounted on poles at intervals along a public road or highway." },
  { id: 134, word: "journey", partOfSpeech: "noun", definition: "an act of traveling from one place to another." },
  { id: 135, word: "courtyard", partOfSpeech: "noun", definition: "an enclosure attached to a house, castle, palace, or other building." },
  { id: 136, word: "shouting", partOfSpeech: "noun", definition: "speaking in a loud voice." },
  { id: 137, word: "asleep", partOfSpeech: "adjective", definition: "lacking sensation or feeling : numb." },
  { id: 138, word: "curious", partOfSpeech: "adjective", definition: "showing interest in finding or searching out information." },
  { id: 139, word: "dinosaur", partOfSpeech: "noun", definition: "a member of a group of extinct reptiles." },
  { id: 140, word: "brilliant", partOfSpeech: "adjective", definition: "showing great intelligence, originality, or resourcefulness." },
  { id: 141, word: "vacuum", partOfSpeech: "verb", definition: "to remove by means of an electrical appliance for cleaning by suction." },
  { id: 142, word: "gorgeous", partOfSpeech: "adjective", definition: "dazzlingly beautiful or attractive." },
  { id: 143, word: "monsoon", partOfSpeech: "noun", definition: "the season of heavy rainfall in India and adjacent countries." },
  { id: 144, word: "dangerous", partOfSpeech: "adjective", definition: "involving risk : demanding caution or care as extremely unsafe." },
  { id: 145, word: "avocado", partOfSpeech: "noun", definition: "the pulpy green or purple somewhat pear-shaped edible fruit of various tropical American trees." },
  { id: 146, word: "valentine", partOfSpeech: "noun", definition: "something sent or given especially to a sweetheart on a day of the same name." },
  { id: 147, word: "February", partOfSpeech: "noun", definition: "the second month of the Gregorian calendar." },
  { id: 148, word: "formation", partOfSpeech: "noun", definition: "a group of troops arranged in a particular order." },
  { id: 149, word: "especially", partOfSpeech: "adverb", definition: "in particular : particularly." },
  { id: 150, word: "hesitate", partOfSpeech: "verb", definition: "to delay or pause typically for a moment." },
  { id: 151, word: "scorcher", partOfSpeech: "noun", definition: "something very hot." },
  { id: 152, word: "scavenger", partOfSpeech: "noun", definition: "an organism that typically feeds on refuse or carrion." },
  { id: 153, word: "fragments", partOfSpeech: "plural noun", definition: "parts broken off : imperfect or incomplete parts." },
  { id: 154, word: "deflated", partOfSpeech: "verb", definition: "released air or gas from." },
  { id: 155, word: "unleash", partOfSpeech: "verb", definition: "to let loose from control or restraint." },
  { id: 156, word: "ration", partOfSpeech: "noun", definition: "the food allowance of one person or one animal for one day." },
  { id: 157, word: "cosmetics", partOfSpeech: "plural noun", definition: "preparations to be applied to the human body for beautifying, preserving, or altering the appearance of a person." },
  { id: 158, word: "crawdad", partOfSpeech: "noun", definition: "any of numerous freshwater crustaceans resembling the lobster but usually much smaller in size." },
  { id: 159, word: "frustration", partOfSpeech: "noun", definition: "something that induces feelings of discouragement." },
  { id: 160, word: "unruly", partOfSpeech: "adjective", definition: "not readily ruled, disciplined, or managed : turbulent, uncontrollable." },
  { id: 161, word: "mascot", partOfSpeech: "noun", definition: "something regarded as a cherished emblem or symbol (as of a group or institution)." },
  { id: 162, word: "aroma", partOfSpeech: "noun", definition: "any smell or odor." },
  { id: 163, word: "mustache", partOfSpeech: "noun", definition: "the hair growing on a man's or a woman's upper lip or that on either side of the upper lip." },
  { id: 164, word: "artifacts", partOfSpeech: "plural noun", definition: "usually simple objects showing human workmanship or modification as distinguished from natural objects." },
  { id: 165, word: "perfume", partOfSpeech: "noun", definition: "a fluid containing essences of flowers or synthetics which is used for its scent." },
  { id: 166, word: "sinister", partOfSpeech: "adjective", definition: "evil or suggestive of evil." },
  { id: 167, word: "tuxedo", partOfSpeech: "noun", definition: "semiformal evening clothing for men consisting of a jacket, a stiff or soft pleated shirt, and usually a cummerbund." },
  { id: 168, word: "discoveries", partOfSpeech: "plural noun", definition: "acts or instances of finding or finding out." },
  { id: 169, word: "lurches", partOfSpeech: "verb", definition: "moves unsteadily or in a series of stops and starts : staggers." },
  { id: 170, word: "language", partOfSpeech: "noun", definition: "the words, their pronunciation, and the methods of combining them used and understood by a considerable community." },
  { id: 171, word: "prognosis", partOfSpeech: "noun", definition: "the act or art of foretelling the course of a disease." },
  { id: 172, word: "sequins", partOfSpeech: "plural noun", definition: "a small ornament usually of shiny metal or plastic pierced with a hole for sewing onto cloth in decorative designs." },
  { id: 173, word: "gallop", partOfSpeech: "noun", definition: "the natural 3-beat gait of a horse." },
  { id: 174, word: "fabulous", partOfSpeech: "adjective", definition: "outstanding or remarkable especially in some acceptable or pleasing quality." },
  { id: 175, word: "lanky", partOfSpeech: "adjective", definition: "tall, somewhat thin, and usually loose-jointed." },
  { id: 176, word: "fluently", partOfSpeech: "adverb", definition: "in a manner that is easy and flowing : pleasingly graceful." },
  { id: 177, word: "mysterious", partOfSpeech: "adjective", definition: "difficult or impossible to understand : obscure." },
  { id: 178, word: "brandished", partOfSpeech: "verb", definition: "shook or waved (a weapon) menacingly." },
  { id: 179, word: "whirlwind", partOfSpeech: "noun", definition: "a small rotating windstorm of limited extent." },
  { id: 180, word: "ferocious", partOfSpeech: "adjective", definition: "exhibiting or given to extreme fierceness and unrestrained violence and brutality." },
  { id: 181, word: "stampede", partOfSpeech: "noun", definition: "a wild headlong rush or flight of frightened animals." },
  { id: 182, word: "treacherous", partOfSpeech: "adjective", definition: "likely to betray trust : unreliable." },
  { id: 183, word: "labyrinth", partOfSpeech: "noun", definition: "a place constructed of or full of intricate passageways and blind alleys." },
  { id: 184, word: "ambush", partOfSpeech: "noun", definition: "a trap in which concealed persons lie in wait to attack by surprise." },
  { id: 185, word: "glimmer", partOfSpeech: "noun", definition: "a faint unsteady light." },
  { id: 186, word: "phantom", partOfSpeech: "noun", definition: "something apparent to sense but with no substantial existence : apparition." },
  { id: 187, word: "cascade", partOfSpeech: "noun", definition: "a steep usually small fall of water." },
  { id: 188, word: "plunder", partOfSpeech: "verb", definition: "to take the goods of by force (as in war) : pillage, sack." },
  { id: 189, word: "nautical", partOfSpeech: "adjective", definition: "of, relating to or associated with sailors, navigation or ships." },
  { id: 190, word: "dubious", partOfSpeech: "adjective", definition: "questionable as to value, quality, origin, or character : open to question." },
  { id: 191, word: "ebony", partOfSpeech: "adjective", definition: "of very low lightness : black, dark — used of color." },
  { id: 192, word: "foreign", partOfSpeech: "adjective", definition: "born in, belonging to, derived from, intended for, or characteristic of some place or country other than the one under consideration." },
  { id: 193, word: "paltry", partOfSpeech: "adjective", definition: "inferior, trashy, worthless." },
  { id: 194, word: "verdict", partOfSpeech: "noun", definition: "an opinion pronounced or felt : decision, judgment." },
  { id: 195, word: "garbled", partOfSpeech: "verb", definition: "mixed up through accident or ignorance : jumbled." },
  { id: 196, word: "encourages", partOfSpeech: "verb", definition: "inspires with mental or moral strength, spirit, or hope." },
  { id: 197, word: "imitation", partOfSpeech: "noun", definition: "an artificial likeness : counterfeit." },
  { id: 198, word: "miniature", partOfSpeech: "adjective", definition: "being or represented on a small scale." },
  { id: 199, word: "receptionist", partOfSpeech: "noun", definition: "one who is employed in a business or professional establishment to greet and help visitors, business callers, or patients." },
  { id: 200, word: "preamble", partOfSpeech: "noun", definition: "a preface or introductory part (as to a written work)." },
  { id: 201, word: "plausible", partOfSpeech: "adjective", definition: "superficially worthy of belief : credible." },
  { id: 202, word: "reprimanding", partOfSpeech: "verb", definition: "chiding for a fault : censuring formally and especially with authority." },
  { id: 203, word: "commotion", partOfSpeech: "noun", definition: "noisy confusion." },
  { id: 204, word: "oblivion", partOfSpeech: "noun", definition: "the quality or state of being forgotten." },
  { id: 205, word: "immigrants", partOfSpeech: "plural noun", definition: "persons that come to a country for the purpose of permanent residence." },
  { id: 206, word: "steeple", partOfSpeech: "noun", definition: "a tall structure usually composed of a series of diminishing stories finished at the top with a small spire or cupola surmounting the lower straight-sided story of a church tower." },
  { id: 207, word: "spectators", partOfSpeech: "plural noun", definition: "people watching an exhibition (such as a sports event)." },
  { id: 208, word: "lanyards", partOfSpeech: "plural noun", definition: "cords worn around the neck by sailors to which is usually attached a knife." },
  { id: 209, word: "suspicious", partOfSpeech: "adjective", definition: "arousing or tending to arouse the imagination or apprehension of something wrong or hurtful without proof or on slight evidence." },
  { id: 210, word: "parchment", partOfSpeech: "noun", definition: "a thin sheet of a type of paper made for recording writing." },
  { id: 211, word: "ramshackle", partOfSpeech: "adjective", definition: "appearing as if ready to collapse : dilapidated : rickety." },
  { id: 212, word: "fugitive", partOfSpeech: "noun", definition: "one who tries to escape justice." },
  { id: 213, word: "heron", partOfSpeech: "noun", definition: "a wading bird that has a long neck and legs, a long tapering bill with a sharp point and sharp cutting edges, large wings and soft plumage." },
  { id: 214, word: "dissolving", partOfSpeech: "verb", definition: "causing to disperse or disappear : getting rid of." },
  { id: 215, word: "nomad", partOfSpeech: "noun", definition: "a member of a people that has no fixed residence but wanders from place to place usually seasonally." },
  { id: 216, word: "billowed", partOfSpeech: "verb", definition: "rose or rolled in waves or surges : surged, undulated." },
  { id: 217, word: "skewer", partOfSpeech: "noun", definition: "a pin of wood or metal for fastening meat to keep in form while roasting or to hold small pieces of meat and vegetables for broiling." },
  { id: 218, word: "lunacy", partOfSpeech: "noun", definition: "wild foolishness : extravagant folly." },
  { id: 219, word: "conjure", partOfSpeech: "verb", definition: "to bring into reality as if by magic." },
  { id: 220, word: "bracken", partOfSpeech: "noun", definition: "a large coarse fern." },
  { id: 221, word: "noggin", partOfSpeech: "noun", definition: "a person's head." },
  { id: 222, word: "neon", partOfSpeech: "adjective", definition: "extremely bright in color." },
  { id: 223, word: "rakish", partOfSpeech: "adjective", definition: "negligent of convention or strict formality : careless, jaunty, sporty." },
  { id: 224, word: "hypnosis", partOfSpeech: "noun", definition: "a trancelike state that resembles sleep but is induced by a person whose suggestions are readily accepted by the subject." },
  { id: 225, word: "rotunda", partOfSpeech: "noun", definition: "a round building; especially : one that is round both outside and inside and is covered by a dome." },
  { id: 226, word: "gusto", partOfSpeech: "noun", definition: "vitality marked by an overabundance of healthy positive and often unrefined vigor and enthusiasm." },
  { id: 227, word: "toiletries", partOfSpeech: "plural noun", definition: "articles or preparations used in the process of washing, grooming, and arranging oneself." },
  { id: 228, word: "gleaned", partOfSpeech: "verb", definition: "picked up or scraped together in piecemeal fashion : acquired bit by bit from some source." },
  { id: 229, word: "jeered", partOfSpeech: "verb", definition: "spoke or cried out with derision or mockery." },
  { id: 230, word: "winsome", partOfSpeech: "adjective", definition: "pleasant." },
  { id: 231, word: "prattling", partOfSpeech: "verb", definition: "talking or saying much and idly." },
  { id: 232, word: "galore", partOfSpeech: "adjective", definition: "abundant, plentiful, profuse." },
  { id: 233, word: "emporium", partOfSpeech: "noun", definition: "a large business or store." },
  { id: 234, word: "atrium", partOfSpeech: "noun", definition: "a large central room with other rooms opening from it." },
  { id: 235, word: "eccentric", partOfSpeech: "adjective", definition: "peculiar or strange." },
  { id: 236, word: "savant", partOfSpeech: "noun", definition: "a person of learning; especially : one with detailed knowledge in some specialized field." },
  { id: 237, word: "almanac", partOfSpeech: "noun", definition: "a publication containing statistical, tabular and general information related to a given calendar period, usually a year." },
  { id: 238, word: "hippies", partOfSpeech: "plural noun", definition: "usually young people who reject the mores of established society and adhere to a nonviolent ethic." },
  { id: 239, word: "samosas", partOfSpeech: "plural noun", definition: "fried pastries that are stuffed with vegetables or spiced meat and shaped like small triangles." },
  { id: 240, word: "campaign", partOfSpeech: "noun", definition: "a period of activity usually continuous and often competitive especially in any seasonal occupation or industry." },
  { id: 241, word: "pistachio", partOfSpeech: "noun", definition: "the edible green seed of a small tree of southern Europe and Asia Minor." },
  { id: 242, word: "mosque", partOfSpeech: "noun", definition: "a building used for public worship by Muslims." },
  { id: 243, word: "zombielike", partOfSpeech: "adjective", definition: "of or relating to a person markedly strange or abnormal in mentality, appearance, or behavior." },
  { id: 244, word: "warlock", partOfSpeech: "noun", definition: "one given to black magic : sorcerer, wizard." },
  { id: 245, word: "colossus", partOfSpeech: "noun", definition: "one marked by great size, strength, or power, and able to dwarf or dominate others." },
  { id: 246, word: "convulsively", partOfSpeech: "adverb", definition: "in a manner producing or accompanied by an unnatural, violent, and involuntary contraction or series of contractions of the muscles." },
  { id: 247, word: "dimensional", partOfSpeech: "adjective", definition: "of or relating to magnitude and size." },
  { id: 248, word: "garishly", partOfSpeech: "adverb", definition: "in a manner that is tastelessly showy or overdecorated : flamboyant." },
  { id: 249, word: "graffitist", partOfSpeech: "noun", definition: "one who makes an inscription, figure, or design scratched on rocks or walls or on artifacts made of plaster, stone, or clay." },
  { id: 250, word: "dexterity", partOfSpeech: "noun", definition: "skill and ease in using the hands." },
  { id: 251, word: "cavorting", partOfSpeech: "verb", definition: "bounding, prancing, or frisking about." },
  { id: 252, word: "marauder", partOfSpeech: "noun", definition: "one who roams about and makes irregular sudden small-scale attacks, raids, or incursions for the sake of obtaining loot." },
  { id: 253, word: "conscience", partOfSpeech: "noun", definition: "the sense of right or wrong within the individual." },
  { id: 254, word: "battlements", partOfSpeech: "plural noun", definition: "parapets that consist of alternate solid parts and open spaces that is used in fortified buildings for defense." },
  { id: 255, word: "deferential", partOfSpeech: "adjective", definition: "showing courteous or ingratiating regard for another's wishes." },
  { id: 256, word: "albatross", partOfSpeech: "noun", definition: "any of a number of large web-footed seabirds that are related to the petrels and that include the largest of the seabirds." },
  { id: 257, word: "khaki", partOfSpeech: "noun", definition: "a durable cotton or woolen cloth used for military uniforms." },
  { id: 258, word: "opalescent", partOfSpeech: "adjective", definition: "having a colored smooth surface that gives the effect of cloudiness and diffusion." },
  { id: 259, word: "asphalt", partOfSpeech: "noun", definition: "a mixture of gravel, sand and petroleum products that is used for pavement." },
  { id: 260, word: "talcum", partOfSpeech: "noun", definition: "a soft mineral that is a basic magnesium silicate and is usually whitish, greenish or grayish with a soapy feel." },
  { id: 261, word: "tranquilizer", partOfSpeech: "noun", definition: "a drug used to reduce anxiety and tension states or mental disturbances in people and animals." },
  { id: 262, word: "equestrian", partOfSpeech: "adjective", definition: "related to horseback riding." },
  { id: 263, word: "plaited", partOfSpeech: "adjective", definition: "braided : interwoven." },
  { id: 264, word: "manticores", partOfSpeech: "plural noun", definition: "legendary animals having the head of a man often with horns, the body of a lion, and the tail of a dragon or scorpion." },
  { id: 265, word: "prestigious", partOfSpeech: "adjective", definition: "esteemed in general opinion : honored." },
  { id: 266, word: "fraidycat", partOfSpeech: "noun", definition: "one that is timid or easily frightened." },
  { id: 267, word: "guttural", partOfSpeech: "adjective", definition: "being a speech sound that is formed in the throat." },
  { id: 268, word: "courier", partOfSpeech: "noun", definition: "one who carries messages, news, or information either with urgent haste or in accordance with a regular schedule." },
  { id: 269, word: "psyche", partOfSpeech: "noun", definition: "the soul, self, or personality." },
  { id: 270, word: "stucco", partOfSpeech: "noun", definition: "a fine plaster of high quality used in the decoration and ornamentation of interior walls." },
  { id: 271, word: "schema", partOfSpeech: "noun", definition: "a diagrammatic depiction of a typical or average situation; broadly: an abridged or generalized presentation : a framework of reference." },
  { id: 272, word: "slough", partOfSpeech: "noun", definition: "a state of moral degradation or spiritual dejection into which one sinks or from which one cannot free oneself." },
  { id: 273, word: "archipelago", partOfSpeech: "noun", definition: "a group or cluster of islands." },
  { id: 274, word: "puissance", partOfSpeech: "noun", definition: "ability to coerce or sway : controlling influence : power." },
  { id: 275, word: "pinioning", partOfSpeech: "verb", definition: "disabling or restraining by binding the arms usually to the body." },
  { id: 276, word: "chignon", partOfSpeech: "noun", definition: "a smooth knot, twist, or arrangement of hair worn at the back of the head especially at the nape of the neck." },
  { id: 277, word: "pheromone", partOfSpeech: "noun", definition: "a chemical substance that is produced by an animal and serves as a specific stimulus to other individuals of the same species." },
  { id: 278, word: "galleon", partOfSpeech: "noun", definition: "a heavy chiefly square-rigged sailing ship of the 15th to early 18th centuries used for war or commerce especially by the Spanish." },
  { id: 279, word: "magnanimous", partOfSpeech: "adjective", definition: "having, showing or suggesting nobility of feeling and generosity of mind." },
  { id: 280, word: "chartreuse", partOfSpeech: "noun", definition: "a variable color averaging a brilliant yellow green." },
  { id: 281, word: "gangly", partOfSpeech: "adjective", definition: "having a spindling or awkwardly long growth : loosely built : lanky." },
  { id: 282, word: "swaggering", partOfSpeech: "adjective", definition: "of, relating to, or having the characteristics of one who conducts oneself in an arrogant or superciliously pompous manner." },
  { id: 283, word: "chimneys", partOfSpeech: "plural noun", definition: "vertical structures incorporated into a building and enclosing flues that carry off smoke or other undesirable fumes or gases." },
  { id: 284, word: "riveted", partOfSpeech: "adjective", definition: "attracted and held engrossingly (as the attention)." },
  { id: 285, word: "plaid", partOfSpeech: "adjective", definition: "having a cross-barred multicolored pattern." },
  { id: 286, word: "dirge", partOfSpeech: "noun", definition: "a song or hymn expressing grief or a solemn sense of loss especially to accompany funeral or memorial rites." },
  { id: 287, word: "zeal", partOfSpeech: "noun", definition: "impassioned eagerness." },
  { id: 288, word: "whittled", partOfSpeech: "verb", definition: "cut or shaped (as a piece of wood) by paring or cutting off chips from the surface of with a knife." },
  { id: 289, word: "depots", partOfSpeech: "plural noun", definition: "bus stations." },
  { id: 290, word: "fiberglass", partOfSpeech: "noun", definition: "glass in fibrous form used in making various products." },
  { id: 291, word: "salvaged", partOfSpeech: "verb", definition: "rescued or saved especially from wreckage or ruin." },
  { id: 292, word: "fissures", partOfSpeech: "plural noun", definition: "narrow openings, chasms, or cracks of some length and considerable depth usually occurring from some breaking, rending, or parting." },
  { id: 293, word: "enthusiastic", partOfSpeech: "adjective", definition: "having an ardent, receptive, responsive temperament." },
  { id: 294, word: "discipline", partOfSpeech: "noun", definition: "a subject that is taught : a branch of learning : field of study." },
  { id: 295, word: "unfamiliar", partOfSpeech: "adjective", definition: "not well known : strange, unaccustomed." },
  { id: 296, word: "scurrying", partOfSpeech: "verb", definition: "moving in or as if in a brisk rapidly alternating step." },
  { id: 297, word: "dignitaries", partOfSpeech: "plural noun", definition: "those who possess exalted rank or hold a position of high regard or honor." },
  { id: 298, word: "pizzeria", partOfSpeech: "noun", definition: "an establishment where usually large open pies typically of thinly rolled dough spread with a spiced mixture are made, baked, and sold." },
  { id: 299, word: "dismissal", partOfSpeech: "noun", definition: "the fact or state of being removed from employment, enrollment, position or office." },
  { id: 300, word: "skittish", partOfSpeech: "adjective", definition: "marked by extreme caution: fearful, wary." },
  { id: 301, word: "careened", partOfSpeech: "verb", definition: "swayed from side to side : lurched." },
  { id: 302, word: "nomination", partOfSpeech: "noun", definition: "an act or right of designating by name for an office or duty : appointment." },
  { id: 303, word: "opportunist", partOfSpeech: "noun", definition: "one who practices taking advantage of circumstances, especially with little regard for principles or ultimate consequences." },
  { id: 304, word: "dictatorship", partOfSpeech: "noun", definition: "a form of government in which a chief magistrate or small clique has absolute power without effective constitutional limitations." },
  { id: 305, word: "comrades", partOfSpeech: "plural noun", definition: "very close friends : companions." },
  { id: 306, word: "sporadic", partOfSpeech: "adjective", definition: "occurring occasionally, singly or in scattered instances." },
  { id: 307, word: "promenade", partOfSpeech: "noun", definition: "a leisurely walk or ride especially in a public place for pleasure, display or exercise." },
  { id: 308, word: "repugnant", partOfSpeech: "adjective", definition: "distasteful to a high degree : exciting distaste or aversion : loathsome." },
  { id: 309, word: "invincible", partOfSpeech: "adjective", definition: "incapable of being vanquished or subjugated : impervious to attack or conquest." },
  { id: 310, word: "renowned", partOfSpeech: "adjective", definition: "celebrated." },
  { id: 311, word: "parachute", partOfSpeech: "noun", definition: "a folding umbrella-shaped device made of light fabric and used for making a safe descent from an airplane." },
  { id: 312, word: "laborious", partOfSpeech: "adjective", definition: "involving or characterized by hard or toilsome effort or by careful and detailed development." },
  { id: 313, word: "appointment", partOfSpeech: "noun", definition: "an arrangement for a meeting : engagement." },
  { id: 314, word: "foreseeable", partOfSpeech: "adjective", definition: "lying within the range for which forecasts are possible." },
  { id: 315, word: "ratify", partOfSpeech: "verb", definition: "to make (as a treaty) valid or legally operative : confirm." },
  { id: 316, word: "scalpel", partOfSpeech: "noun", definition: "a small straight knife with a thin keen blade used especially for dissecting." },
  { id: 317, word: "reclusive", partOfSpeech: "adjective", definition: "marked by seclusion or retirement : solitary." },
  { id: 318, word: "compassionate", partOfSpeech: "adjective", definition: "marked by a ready inclination to pity, sympathy, or tenderness." },
  { id: 319, word: "bulletin", partOfSpeech: "noun", definition: "a brief public notice concerning a matter of marked current interest and usually issuing from an authoritative source." },
  { id: 320, word: "alfalfa", partOfSpeech: "noun", definition: "an important leguminous forage plant grown widely and principally for hay and adapted to widely varying conditions of climate and soil." },
  { id: 321, word: "officially", partOfSpeech: "adverb", definition: "with formal authorization : formally." },
  { id: 322, word: "crematorium", partOfSpeech: "noun", definition: "a building containing a furnace for reducing the bodies of the dead to ashes by the action of fire." },
  { id: 323, word: "bayonet", partOfSpeech: "noun", definition: "a steel blade made to be attached to the muzzle end of a type of firearm that is fired while braced against the shoulder." },
  { id: 324, word: "amicable", partOfSpeech: "adjective", definition: "characterized by friendship and goodwill." },
  { id: 325, word: "beautician", partOfSpeech: "noun", definition: "someone who is trained to style hair or give beauty treatments." },
  { id: 326, word: "equations", partOfSpeech: "plural noun", definition: "statements of equivalence between two mathematical expressions, the sign = usually being placed between them." },
  { id: 327, word: "assignment", partOfSpeech: "noun", definition: "a specified amount of work or a definite task or mission prescribed by authority or undertaken as though so prescribed." },
  { id: 328, word: "ultimatum", partOfSpeech: "noun", definition: "a last demand or proposal whose rejection will end negotiations and trigger an action such as force." },
  { id: 329, word: "whinnying", partOfSpeech: "verb", definition: "neighing especially in a low or gentle fashion." },
  { id: 330, word: "squalor", partOfSpeech: "noun", definition: "the quality or state of being marked by filthiness and degradation usually from neglect." },
  { id: 331, word: "memoirs", partOfSpeech: "plural noun", definition: "histories or narratives composed from or stressing personal experience and acquaintance with the events, scenes, or persons described." },
  { id: 332, word: "cylinders", partOfSpeech: "plural noun", definition: "objects or forms having flat circular ends and straight sides." },
  { id: 333, word: "ominous", partOfSpeech: "adjective", definition: "indicative of future misfortune or calamity : causing anxiety and fear." },
  { id: 334, word: "muffler", partOfSpeech: "noun", definition: "any of various devices to deaden the noise of escaping gases or vapor." },
  { id: 335, word: "syndrome", partOfSpeech: "noun", definition: "a group of symptoms or signs typical of a disease, disturbance, or condition in animals or plants." },
  { id: 336, word: "premises", partOfSpeech: "plural noun", definition: "a building and the area of land it sits on." },
  { id: 337, word: "safari", partOfSpeech: "noun", definition: "a hunting or other expedition in east Africa especially on foot." },
  { id: 338, word: "lasagna", partOfSpeech: "noun", definition: "a baked dish containing layers of boiled pasta ribbons, cheese, a seasoned sauce of tomatoes, and meat or vegetables." },
  { id: 339, word: "substantially", partOfSpeech: "adverb", definition: "in a manner considerable in amount, value, or worth." },
  { id: 340, word: "mercantile", partOfSpeech: "adjective", definition: "of or relating to merchants or trading : appropriate to or characteristic of merchants : engaged in trade." },
  { id: 341, word: "formidable", partOfSpeech: "adjective", definition: "tending to inspire awe or wonder usually by reason of notable size, quantity, superiority or excellence." },
  { id: 342, word: "propaganda", partOfSpeech: "noun", definition: "the spreading of rumor, ideas or information for the purpose of either helping or injuring a person, institution or cause." },
  { id: 343, word: "marquee", partOfSpeech: "adjective", definition: "having the star power of someone who is famous." },
  { id: 344, word: "proficient", partOfSpeech: "adjective", definition: "well advanced in an art, an occupation, a skill, or a branch of knowledge." },
  { id: 345, word: "compunction", partOfSpeech: "noun", definition: "remorse, reluctance, misgiving." },
  { id: 346, word: "emphatically", partOfSpeech: "adverb", definition: "in an insistent manner." },
  { id: 347, word: "hyperventilated", partOfSpeech: "verb", definition: "underwent excessive rate and depth of respiration leading to abnormal loss of carbon dioxide from the blood." },
  { id: 348, word: "ostracism", partOfSpeech: "noun", definition: "exclusion from common privileges or social acceptance." },
  { id: 349, word: "onslaught", partOfSpeech: "noun", definition: "an especially fierce attack." },
  { id: 350, word: "ruefully", partOfSpeech: "adverb", definition: "in a pitiable or woeful manner." },
  { id: 351, word: "misanthrope", partOfSpeech: "noun", definition: "one who hates or despises mankind." },
  { id: 352, word: "prototype", partOfSpeech: "noun", definition: "the first full-scale model of a new type or design of furniture, machinery, or vehicle." },
  { id: 353, word: "mulberry", partOfSpeech: "noun", definition: "the edible usually dark purple fruit of a tree of the same name." },
  { id: 354, word: "hypocritical", partOfSpeech: "adjective", definition: "of or relating to the act or practice of pretending to be what one is not or to have principles or beliefs that one does not have." },
  { id: 355, word: "chlorine", partOfSpeech: "noun", definition: "a common nonmetallic element best known as a heavy greenish irritating toxic gas of disagreeable odor used chiefly as a powerful bleaching, oxidizing, and disinfecting agent." },
  { id: 356, word: "traumatic", partOfSpeech: "adjective", definition: "of, relating to, or resulting from an injury or wound to the human body caused by the application of external force or violence." },
  { id: 357, word: "receipts", partOfSpeech: "plural noun", definition: "writings acknowledging the taking or accepting of goods or money delivered or paid." },
  { id: 358, word: "solemnly", partOfSpeech: "adverb", definition: "in a manner marked by grave sobriety and earnest serious sedateness : free from casualness or lighthearted levity." },
  { id: 359, word: "begrudge", partOfSpeech: "verb", definition: "to look upon or acknowledge with reluctance, hesitation, or disapproval." },
  { id: 360, word: "contentious", partOfSpeech: "adjective", definition: "marked by a wearisome tendency to disputes." },
  { id: 361, word: "precocious", partOfSpeech: "adjective", definition: "manifesting at an early age some of the mental or physical characteristics usually associated with maturity." },
  { id: 362, word: "ensemble", partOfSpeech: "noun", definition: "a group of supporting players or the chorus." },
  { id: 363, word: "cadre", partOfSpeech: "noun", definition: "a nucleus or core group especially of trained personnel or active members of an organization who are capable of assuming leadership." },
  { id: 364, word: "lye", partOfSpeech: "noun", definition: "a strong alkaline liquor that contains chiefly potassium carbonate obtained by leaching wood ashes with water." },
  { id: 365, word: "belfry", partOfSpeech: "noun", definition: "a bell tower." },
  { id: 366, word: "lacrosse", partOfSpeech: "noun", definition: "a game played with two teams of ten players each with each player using a long-handled stick to catch and throw a ball." },
  { id: 367, word: "sluice", partOfSpeech: "noun", definition: "a body of water pent up behind a floodgate or water gate." },
  { id: 368, word: "cajolery", partOfSpeech: "noun", definition: "the act or practice of alluring or inducing by soft words or flattery." },
  { id: 369, word: "vigilance", partOfSpeech: "noun", definition: "watchfulness in respect of danger or hazard." },
  { id: 370, word: "residuals", partOfSpeech: "plural noun", definition: "payments (as to an actor or writer) for each rerun especially of a commercial." },
  { id: 371, word: "boutique", partOfSpeech: "noun", definition: "a small retail store; especially : a specialty shop dealing in ladies' fashionable ready-to-wear clothes and accessories." },
  { id: 372, word: "peroxide", partOfSpeech: "noun", definition: "a binary compound containing a relatively high proportion of oxygen." },
  { id: 373, word: "aristocracy", partOfSpeech: "noun", definition: "an upper class usually made up of a hereditary nobility." },
  { id: 374, word: "apocalypse", partOfSpeech: "noun", definition: "something with the quality of a revelation by prophecy." },
  { id: 375, word: "tuberculosis", partOfSpeech: "noun", definition: "a communicable disease caused by a bacillus and characterized by toxic symptoms or allergic manifestations which in humans primarily affect the lungs." },
  { id: 376, word: "barricade", partOfSpeech: "noun", definition: "an object or objects placed so as to prevent entry or passage." },
  { id: 377, word: "anonymously", partOfSpeech: "adverb", definition: "in a manner that is of unknown or unnamed source or origin." },
  { id: 378, word: "unparalleled", partOfSpeech: "adjective", definition: "having no equal or match." },
  { id: 379, word: "barrette", partOfSpeech: "noun", definition: "a clip used to hold hair in place." },
  { id: 380, word: "chassis", partOfSpeech: "noun", definition: "the frame upon which is mounted the body (as of an automobile or airplane)." },
  { id: 381, word: "junket", partOfSpeech: "noun", definition: "a pleasure trip or tour made by an official at public expense ostensibly for purposes of inspection, investigation, or other public business." },
  { id: 382, word: "quandary", partOfSpeech: "noun", definition: "a state of doubt or bewilderment : a dilemma." },
  { id: 383, word: "gingham", partOfSpeech: "noun", definition: "a clothing fabric usually of yarn-dyed cotton in plain weave made in solid colors, checks, plaids, and stripes." },
  { id: 384, word: "silhouette", partOfSpeech: "noun", definition: "a likeness of a person or thing showing only the outline, and that is typically filled in with black." },
  { id: 385, word: "auxiliary", partOfSpeech: "adjective", definition: "offering or providing help, assistance, or support especially by interaction." },
  { id: 386, word: "thesaurus", partOfSpeech: "noun", definition: "a book containing a store of words or of information about a particular field or set of concepts; specifically : a dictionary of synonyms." },
  { id: 387, word: "patriarchs", partOfSpeech: "plural noun", definition: "men regarded as fathers or founders (as of a race, science, religion or class of people)." },
  { id: 388, word: "chandelier", partOfSpeech: "noun", definition: "a lighting fixture suspended from the ceiling and having two or more usually upcurving arms bearing lights, originally candles." },
  { id: 389, word: "concierge", partOfSpeech: "noun", definition: "an attendant at the entrance of a building : a doorkeeper." },
  { id: 390, word: "latticework", partOfSpeech: "noun", definition: "an assemblage of structures of wood or metal made by crossing thin strips so as to form a network." },
  { id: 391, word: "hibiscus", partOfSpeech: "noun", definition: "any plant or flower of a large widely distributed genus of herbs, shrubs or small trees with dentate or lobed leaves and large showy flowers." },
  { id: 392, word: "tamale", partOfSpeech: "noun", definition: "ground meat seasoned with chili or other filling, rolled up in cornmeal dough, wrapped in corn husks, and steamed." },
  { id: 393, word: "maracas", partOfSpeech: "plural noun", definition: "rattles of Latin American origin that are often made from a hollow gourd containing pebbles or dried seeds and that are used as a percussion instrument usually in pairs." },
  { id: 394, word: "gyroplane", partOfSpeech: "noun", definition: "a fixed-wing aircraft balanced and supported by the aerodynamic forces acting on rapidly rotating horizontal or slightly inclined planes." },
  { id: 395, word: "burpees", partOfSpeech: "plural noun", definition: "conditioning exercises in which a person repeats a sequence of squats, push-ups, and vertical jumps." },
  { id: 396, word: "piccolo", partOfSpeech: "noun", definition: "a small shrill flute pitched an octave higher than the ordinary flute." },
  { id: 397, word: "tulle", partOfSpeech: "noun", definition: "a sheer and often stiffened machine-made net made with a usually hexagonal mesh and of silk, rayon, or nylon and used chiefly for veils, evening dresses, or ballet costumes." },
  { id: 398, word: "camphor", partOfSpeech: "noun", definition: "a tough gumlike substance obtained especially from the wood and bark of a tree of the same name and used as a stimulant in medicine and as an insect repellent." },
  { id: 399, word: "paparazzi", partOfSpeech: "plural noun", definition: "free-lance photographers who aggressively pursue celebrities in order to take candid photographs." },
  { id: 400, word: "pumpernickel", partOfSpeech: "noun", definition: "a sourdough bread made with rye and wheat flours." },
  { id: 401, word: "bursitis", partOfSpeech: "noun", definition: "inflammation of a fluid-filled cavity in a joint of the body." },
  { id: 402, word: "cycads", partOfSpeech: "plural noun", definition: "any plants abundant in the Mesozoic but now reduced to a few localized and widely scattered tropical forms that have an unbranched trunk." },
  { id: 403, word: "sarsaparilla", partOfSpeech: "noun", definition: "a sweetened carbonated beverage similar to root beer with the predominant flavor from birch oil and sassafras." },
  { id: 404, word: "cannelloni", partOfSpeech: "noun", definition: "tubes especially of pasta filled with a savory stuffing (as of meat)." },
  { id: 405, word: "bronchitis", partOfSpeech: "noun", definition: "acute or chronic inflammation of either of the two primary divisions of the trachea that lead respectively into the right and the left lung." },
  { id: 406, word: "diphtheria", partOfSpeech: "noun", definition: "a contagious disease in children that causes a sore, swollen throat." },
  { id: 407, word: "baklava", partOfSpeech: "noun", definition: "a dessert made of thin pastry layered with nuts and honey." },
  { id: 408, word: "corbels", partOfSpeech: "plural noun", definition: "architectural elements which project from within a wall and support a superincumbent weight." },
  { id: 409, word: "trebuchets", partOfSpeech: "plural noun", definition: "medieval military engines designed to hurl stones and similar missiles with great force by means of a heavy weight fastened to the short arm of a lever." },
  { id: 410, word: "fraulein", partOfSpeech: "noun", definition: "a usually young unmarried woman especially of Germany." },
  { id: 411, word: "protege", partOfSpeech: "noun", definition: "one who is protected or trained or whose career is furthered by a person of experience, prominence, or influence : pupil." },
  { id: 412, word: "boll weevil", partOfSpeech: "noun", definition: "a grayish snout beetle about 1/4 inch long that infests the cotton plant, puncturing and laying its eggs in the squares and pods." },
  { id: 413, word: "dulce", partOfSpeech: "noun", definition: "sweetmeat, candy — used in the Southwest." },
  { id: 414, word: "boulangerie", partOfSpeech: "noun", definition: "a bakery that specializes in bread and especially in French-style breads." },
  { id: 415, word: "pogrom", partOfSpeech: "noun", definition: "an organized massacre and looting of helpless people usually with the connivance of officials." },
  { id: 416, word: "maquisards", partOfSpeech: "plural noun", definition: "French guerrilla fighters in World War II resisting the Nazis." },
  { id: 417, word: "Aubusson", partOfSpeech: "noun", definition: "a tapestry woven originally in the 16th century, noted for its figure and scenic designs, and used for wall hangings and upholstery." },
  { id: 418, word: "Charolais", partOfSpeech: "noun", definition: "a breed of large white cattle developed in France for draft purposes but now kept chiefly as a beef breed and important for crossbreeding." },
  { id: 419, word: "Buffalo", partOfSpeech: "noun", definition: "city and port on Lake Erie and the Niagara River in western New York." },
  { id: 420, word: "Berlin", partOfSpeech: "noun", definition: "city comprising a state of Germany; capital of Germany on the Spree River." },
  { id: 421, word: "Adriatic", partOfSpeech: "adjective", definition: "of or relating to the sea that lies east of Italy." },
  { id: 422, word: "Tucson", partOfSpeech: "noun", definition: "city in southeastern Arizona." },
  { id: 423, word: "Erie", partOfSpeech: "noun", definition: "a city and port on a lake in east central North America on the boundary between the U.S. and Canada; one of the Great Lakes." },
  { id: 424, word: "Oswego", partOfSpeech: "noun", definition: "city on Lake Ontario in northern New York." },
  { id: 425, word: "Kilimanjaro", partOfSpeech: "noun", definition: "a volcanic mountain in Tanzania near the border of Kenya whose central peak is the highest point in Africa." },
  { id: 426, word: "Nehru", partOfSpeech: "adjective", definition: "having a long narrow cut and a mandarin collar — usually used of a jacket." },
  { id: 427, word: "Frankenstein", partOfSpeech: "noun", definition: "a work or agency that proves troublesomely uncontrollable especially to its creator; especially : one that ultimately destroys or ruins its creator." },
  { id: 428, word: "Everest", partOfSpeech: "noun", definition: "the highest point : climax, apex." },
  { id: 429, word: "Yiddish", partOfSpeech: "noun", definition: "a High German language spoken by Jews chiefly in eastern Europe and areas to which Jews from eastern Europe have migrated." },
  { id: 430, word: "senor", partOfSpeech: "noun", definition: "mister — used as a title of courtesy prefixed to the name of a Spanish or Spanish-speaking man." },
  { id: 431, word: "au revoir", partOfSpeech: "noun", definition: "good-bye." },
  { id: 432, word: "lo mein", partOfSpeech: "noun", definition: "a Chinese dish consisting of sliced vegetables, soft noodles, and usually meat or shrimp in bite-size pieces stir-fried in a seasoned sauce." },
  { id: 433, word: "sans serif", partOfSpeech: "noun", definition: "a letter or typeface with letters that have no short lines stemming from and at an angle to the upper and lower ends of the strokes of each letter." },
  { id: 434, word: "et cetera", partOfSpeech: "noun", definition: "and others especially of the same kind : and so on : and so forth." },
  { id: 435, word: "hors d'oeuvres", partOfSpeech: "plural noun", definition: "any of various savory foods usually served as appetizers at the beginning of a meal." },
  { id: 436, word: "maitre d'", partOfSpeech: "noun", definition: "the head of the dining-room staff of a restaurant or hotel." },
  { id: 437, word: "monsieur", partOfSpeech: "noun", definition: "mister." },
  { id: 438, word: "serape", partOfSpeech: "noun", definition: "a woolen blanket often of bright geometric patterns worn by Spanish-American men as a cloak or poncho." },
  { id: 439, word: "vidimus", partOfSpeech: "noun", definition: "an official or legal inspection (as of a document); also : an attested copy of a document." },
  { id: 440, word: "delphine", partOfSpeech: "adjective", definition: "of or relating to any of various small marine toothed whales that have the snout more or less elongated into a beak." },
  { id: 441, word: "wainscoting", partOfSpeech: "verb", definition: "lining (as a wall) with or as if with boards or paneling." },
  { id: 442, word: "toiletries", partOfSpeech: "plural noun", definition: "articles or preparations used in the process of washing, grooming, and arranging oneself." },
  { id: 443, word: "bracken", partOfSpeech: "noun", definition: "a large coarse fern." },
  { id: 444, word: "stucco", partOfSpeech: "noun", definition: "a fine plaster of high quality used in the decoration and ornamentation of interior walls." },
  { id: 445, word: "pâtisserie", partOfSpeech: "noun", definition: "a shop that sells French pastry." },
  { id: 446, word: "colossus", partOfSpeech: "noun", definition: "one marked by great size, strength, or power, and able to dwarf or dominate others." },
  { id: 447, word: "cajolery", partOfSpeech: "noun", definition: "the act or practice of alluring or inducing by soft words or flattery." },
  { id: 448, word: "Charollais", partOfSpeech: "noun", definition: "a breed of large white cattle developed in France for draft purposes but now kept chiefly as a beef breed." },
  { id: 449, word: "artefacts", partOfSpeech: "plural noun", definition: "usually simple objects showing human workmanship or modification as distinguished from natural objects." },
  { id: 450, word: "moustache", partOfSpeech: "noun", definition: "the hair growing on a man's or a woman's upper lip or that on either side of the upper lip." },
];

// Group words into sets of 10 for practice sessions
export const WORD_GROUPS = Array.from({ length: Math.ceil(ALL_WORDS.length / 10) }, (_, i) =>
  ALL_WORDS.slice(i * 10, i * 10 + 10)
);

export const TOTAL_GROUPS = WORD_GROUPS.length;
